[package]
name = "event_bus_adapter_demo_subscriber"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
lapin = "2.3.4"
tokio = { version = "1.38.0", features = ["full" ] }
tokio-executor-trait = "2.1.1"
tokio-reactor-trait = "1.1.0"
