services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  event_bus_adapter_demo_publisher:
    build: .
    container_name: event_bus_adapter_demo_subscriber
    platform: linux/amd64
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: ["/usr/local/bin/event_bus_adapter_demo_subscriber"]
